theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: '/assets/images/logo.svg'
  home:
    head:
      title: site
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
